language: node_js
node_js:
  - "0.10"
env:
  global:
    - secure: "HOdDp2doi4EqKAfbzkTZtRg+MWWJGA1t7xWQfvJyTG5A6Kvi0mhr6NAl0sUG8Q+1/Cbw0y2Mbag0Sq7xX8RZULfEAOU2DkoxN5vlNr7puKBjnDC3qJFrAxAKctooNTf6d77Tx3P9tlOR3yaFQRkc5cC2tHB8ttg6dxro5FeAs/A="
before_install:
  - npm install -g gulp
  - npm install -g coveralls
before_script:
  - npm install gulp
script:
  - gulp travis
after_success:
  - coveralls < ./coverage/lcov.info
